config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin?} do
    get 'admin', to: "admin#index"
    get 'admin/posts'
    get 'admin/comments'
    get 'admin/users'
    get 'admin/show_post/:id', to:"admin#show_post", as: "admin_post"
  end
  get 'search', to: "search#index"
  get 'users/profile'
  get 'my_posts/:user_id', to: "posts#my_posts" , as: :my_posts
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  get "/u/:id", to: "users#profile", as: "user"
  resources :posts do
    resources :comments
  end
  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get "pages/home", to: "pages#home"
 
  root "pages#home"
end

app/models/post.rb
class Post < ApplicationRecord
    extend FriendlyId
    validates :title , presence: true , length: {minimum: 5, maximum: 50}
    validates :body , presence:true , length: {minimum: 50, maximum: 500}
    belongs_to :user
    has_many :comments , dependent: :destroy


    has_noticed_notifications model_name: "Notification"
    has_many :notifications, through: :user 

    def self.ransackable_attributes(auth_object = nil)
        [ "body", "id", "id_value", "title", "updated_at", "user_id", "views"]
    end

    def self.ransackable_associations(auth_object = nil)
        ["comments",  "user"]
    end

    friendly_id :title, use: %i[slugged history]

    def should_generate_new_friendly_id?
        title_changed? || slug.blank?
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[show index]

  def my_posts
    @posts = Post.includes([:user]).where(user_id: params[:user_id])
  end

  # GET /posts or /posts.json
  def index
    @posts = Post.includes([:user]).all.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    
    @post.update(views: @post.views + 1)
    @comments = @post.comments.includes([:user, :rich_text_body])
    mark_notification_as_read
  end

  # GET /posts/new
  def new
    @post = Post.new( body: "questo è un nuovo post")
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      par = post_params
      #par[:slug] = par[:title]
      if @post.update(par)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|

      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
      redirect_to @post, status: :moved_permanently if params[:id] !=@post.slug
    end

    def set_my_posts
      @post = Post.where(params[:user_name])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :slug)
    end

    def mark_notification_as_read
      if current_user
        notifications_to_mark_as_read = @post.notifications_as_post.where(recipient: current_user)
        notifications_to_mark_as_read.each do |notification|  
          notification.mark_as_read!
        end
      end
    end

    
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="card" style="width: 30rem;">
  <h2><%= post.title %></h2>
  <div class="card-body">
    
    <h5 class="card-title">Posted by <%= link_to post.user.name , user_path(post.user) %></h5>
    <span class="badge bg-warning text-dark"><%= pluralize(post.views, "view") %></span>
    <p class="card-text"><%= post.body %></p>
    
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>
<h1> l'id del post è <%= @post.id %> </h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path , class:"btn btn-primary"%>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <h1>Posts</h1>
  <div id="posts">
    <% @posts.each do |post| %>
      <%= render post %>
      <p>
        
        <%= link_to "Show this post", post_path(post.id) , class:"btn btn-primary"%>
      </p>
    <% end %>
  </div>
  
</div>

<div class="container">
    <div class="d-flex flex-column">
    
            <%= link_to "New post", new_post_path , class:"btn btn-secondary"%>
        
    </div>
</div>

app/views/posts/my_posts.html.erb
    <div class="form-outline mb-4">
                
                <h1>My posts</h1>
    </div>
    <%@posts.each do |post|%>
    <div class="card  " >
            <div class="card-body mb-4">
                <div class ="card-body mb-4">
                    <%= render post %>
                    <div>
                        <div class="btn-group" role="group" aria-label="Basic mixed styles example"">
                            <%= link_to "Edit this post", edit_post_path(post) , class:"btn btn-warning"%> 
                            <%= link_to "Back to posts", posts_path , class:"btn btn-primary" %> 
                            <%=button_to "Destroy this post", post, method: :delete , class:"btn btn-secondary"  %> 
                            <%= link_to "Show this post", post , class:"btn btn-info"%> 
                        </div>
                    </div>
                </div>
            </div>
        <%end%>
    </div>
<div class="card-body mb-4">
    <div class="container">
        <div class="d-flex flex-column">
        
                <%= link_to "Create a new Post", new_post_path(@post) , class:"btn btn-primary"%> 
            
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1>New post</h1>



  <%= render "form", post: @post %>

  <br>

  <div>
    <%= link_to "Back to posts", posts_path , class:"btn btn-primary"%>
  </div>
</div>

app/views/posts/show.html.erb
<div class ="container">
  <%= render @post %>
  <div>
    <%= link_to "Edit this post", edit_post_path(@post) , class:"btn btn-primary"%> |
    <%= link_to "Back to posts", posts_path , class:"btn btn-primary" %>
    <p>
    <%= button_to "Destroy this post", @post, method: :delete , class:"btn btn-secondary"  %>
    </p>
  </div>
</div>

<div class="container">
  <% @comments.each do |comment|%>
    <%= render "comments/comment", post: @post, comment: comment %>
  <%end%>
  <%if current_user%>
    <%= render "comments/form", post: @post, comment: @post.comments.build , submit_label: "Reply"%>
  <%else%>
    
    <strong class="container "> you need to be 
      <div class="badge bg-primary text-wrap">
        <%= link_to "Logged in" , new_user_session_path, class:"link-light"%>
      </div> to write a comment or sign 
      <div class="badge bg-primary text-wrap">
        <%= link_to "Here" , new_user_registration_path, class:"link-light"%>
      </div> to write a comment or sign 
    </strong>
    
  <%end%>
</div>